version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t $DOCKER_USERNAME/karsajobs-ui:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/karsajobs-ui:latest

workflows:
  karsajobs_ui_ci:
    jobs:  
      - lint-dockerfile
      - build-app-karsajobs-ui